# kubectl create namespace iron-namespace
#kubectl config set-contect --current --namespace=iron-namespaceapiVersion: apps/v1
kind: Deployment 
metadata: 
 name: galler-deploy
 labels:
  run : iron-gallery
spec:
 replicas: 1
 selector: 
  matchLabels:
   run: iron-gallery
 template:
  metadata:
   labels:
    run: iron-gallery
  spec:
   containers:
   - name: iron-galler-container
     image: kodekloud/irongallery:2.0
     resources:
       limits:
         cpu: 50m
         memory: 100mi
     volumeMounts:
     - name: config
       mountPath: /usr/share/nginx/html/data
     - name: images
       mountPath: /usr/share/nginx/html/uploads
   volumes:
   - name: config 
     emptyDir:
   
   - name: images
     emptyDir:
