apiVersion: v1
kind: Pod
metadata: 
 name: nginx-phform-pod
spec:
 volumes:
  - name: shared-files
    emptyDir:
  - name: nginx-config-volume
    configMap:
     name: nginx-config     
 containers:
  - name: nginx-container 
    image: nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts: 
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: /etc/nginx/nginx.conf

  - name: phpfm-container
    image: php:7.0-fpm
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html

---
apiVersion: v1
kind: configMap
metadata: nginx-config
data:
  nginx.conf: |
   events {} 
    http {
      server {
        listen 8092;
        index index.html index.htm index.php;
        root  /var/www/html;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
